<<<<<<< HEAD
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
=======
// app/layout.tsx
import { ClerkProvider } from '@clerk/nextjs';
import './globals.css';
import Footer from "@/components/Footer";
import dynamic from 'next/dynamic';
import { ReactNode } from 'react'
import { PHProvider } from './providers';
import ClientLayout from './ClientLayout';

const PostHogPageView = dynamic(() => import('./PostHogPageView') as Promise<typeof import('./PostHogPageView')>, {
  ssr: false,
  loading: () => null,
});

export const metadata = {
  title: "Newspodify",
  description: "Newsletters Transformed into Engaging Podcasts",
  openGraph: {
    title: 'Newspodify',
    description: 'Newsletters Transformed into Engaging Podcasts',
    images: [
      {
        url: '/noads.webp', // Update this to the actual path of your featured image
        width: 600,
        height: 600,
        alt: 'Newspodify featured image',
      },
    ],
  },
>>>>>>> 68701eb29d54020edcf3928d54200aa5a1f2bf91
};

export default function RootLayout({
  children,
<<<<<<< HEAD
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
=======
}: {
  children: ReactNode
}) {
  return (
    <html lang="en">
      <PHProvider>
        <body>
          <ClerkProvider>
            <ClientLayout>
              <div className="relative flex flex-col min-h-screen">
                <PostHogPageView />
                <main className="flex-1 bg-black-3">
                  <section>
                    <div>
                      <div>
                        {children}
                        {/*TOASTER*/}
                      </div>
                    </div>
                  </section>
                  {/*RIGHTSIDEBAR*/} 
                </main>
                <Footer />
              </div>
            </ClientLayout>
          </ClerkProvider>
        </body>
      </PHProvider>
>>>>>>> 68701eb29d54020edcf3928d54200aa5a1f2bf91
    </html>
  );
}
